## 服务器前置任务（ubuntu使用）
- name: pre-onlyoffice
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
    - name: Install Python
      raw: sudo apt update && sudo apt-get -y install python
      ignore_errors: yes

## 部署
- name: ONLYOFFICE
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: onlyoffice, tags: "onlyoffice"}
    - {role: role_docker, tags: "role_docker"}
    - {role: role_docker_onlyofficedocumentserver, tags: "role_docker_onlyofficedocumentserver"}
    - {role: role_init_password, tags: "role_init_password"}
    - {role: role_preend, tags: "role_prend"}
    - {role: role_end, tags: "role_end"}