## 服务器前置任务（ubuntu使用）
- name: pre-onlyoffice
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
    - name: Install Python
      raw: sudo apt update && sudo apt-get -y install python
      ignore_errors: yes

## 部署
- name: ONLYOFFICE
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - {role: cloud, tags: "cloud"}
    - {role: common, tags: "common"}
    - {role: onlyoffice, tags: "onlyoffice"}
    - {role: initdb, tags: "initdb"}
    - {role: end, tags: "end"}