#onlyoffice 官方提供两种安装脚本
script_url_debian: https://download.onlyoffice.com/install/install-Debian.sh
script_url_redhat: https://download.onlyoffice.com/install/install-RedHat.sh

root_password: QFL6itcHsN,BL8
onlyoffice_password: Ag3Fc49L&7YMGK