---
- name: Delete onlyoffice dir for sec_installation
  shell: rm -rf /data/wwwroot/onlyoffice

- name: Clone onlyoffice in Websoft9 
  git:
    repo: "{{onlyoffice_url}}"
    dest: "/data/wwwroot/onlyoffice"

- name: Run the docker-compose
  shell: |
    docker-compose up -d
    sleep 30
  args:
    chdir: /data/wwwroot/onlyoffice

- name: Check onlyofficecommunityserver Version
  shell: sudo echo "onlyofficecommunityserver version:" $(docker images |grep onlyoffice/communityserver |awk '{print $2}') | tee -a /data/logs/install_version.txt

- name: Check onlyofficedocumentserver Version
  shell: sudo echo "onlyofficedocumentserver version:" $(docker images |grep onlyoffice/documentserver |awk '{print $2}') | tee -a /data/logs/install_version.txt

- name: Check onlyofficecommunityserver Service
  shell: sudo docker ps | grep onlyoffice-community-server
  register: check_onlyofficecommunityserver_service
  notify: check_onlyofficecommunityserver_service

- name: Check onlyofficedocumentserver Service
  shell: sudo docker ps | grep onlyoffice-document-server
  register: check_onlyofficedocumentserver_service
  notify: check_onlyofficedocumentserver_service
