---
# OnlyOffice need python-urllib3-1.10.2-7, so need to uninstall the latest urllib3 

- name: Create Directory /data/wwwroot/onlyoffice
  file:
    path: /data/wwwroot/onlyoffice
    state: directory
    mode: 0755

- name: copy docker-compose.yml to /data/onlyoffice/
  template:
    src: docker-compose.yml
    dest: /data/wwwroot/onlyoffice

- name: run the docker-compose
  shell: 
    cmd: docker-compose up
    chdir: /data/wwwroot/onlyoffice
