---
# OnlyOffice need python-urllib3-1.10.2-7, so need to uninstall the latest urllib3 

- name: Create Directory for CommunityServer
  file:
    path: 
      - /data/wwwroot/onlyoffice/CommunityServer/logs
      - /data/wwwroot/onlyoffice/CommunityServer/data
      - /data/wwwroot/onlyoffice/CommunityServer/DocumentServer/data
    state: directory
    mode: 0755


- name: Create Directory for DocumentServer
  file:
    path: 
      - /data/wwwroot/onlyoffice/DocumentServer/logs
      - /data/wwwroot/onlyoffice/DocumentServer/data
    state: directory
    mode: 0755

- name: copy docker-compose.yml to /data/onlyoffice/
  template:
    src: docker-compose.yml
    dest: /data/onlyoffice/docker-compose.yml

- name: run the docker-compose
  shell: 
    cmd: docker-compose -f onlyoffice-compose.yml
    chdir: /data/onlyoffice