---
- block:
  - name: Download OnlyOffice's auto-install script of Ubuntu&Debian
    get_url:
      url: "{{script_url_debian}}"
      dest: /tmp/
      mode: 0755
    
  - name: install script
    command: /tmp/bash install-Debian.sh -os true

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- block:
  - name: Download OnlyOffice's auto-install script of Redhat&Centos
    get_url:
      url: "{{script_url_redhat}}"
      dest: /tmp/
      mode: 0755
    
  - name: install script
    command: /tmp/install-RedHat.sh -os true 

  when: ansible_os_family == 'RedHat'

# 处理数据库随机密码问题

#添加 onlyoffice 数据库用户，授权，更改 /var/www/onlyoffice/WebStudio/web.connections.config 文件中的数据库配置信息
- name: get default root password of mysql
  shell: grep "Password" /var/www/onlyoffice/WebStudio/web.connections.config | awk -F\; '{print $4}' | awk -F'=' '{print $2}'
  register: root_password

- name: create mysql user "onlyoffice"
  mysql_user:
    name: onlyoffice
    password: "{{root_password.stdout}}"
    login_user: root
    login_password: "{{root_password.stdout}}"
    priv: 'onlyoffice.*:ALL'
    
- name: replace user id in web.connections.config
  replace:
    path: /var/www/onlyoffice/WebStudio/web.connections.config
    before: ';Password'
    after: 'User ID='
    regexp: 'root'
    replace: 'onlyoffice'

- name: restart mysql monoserve monoserveApiSystem
  service:
    name: mysql 
    state: restarted
    enabled: yes

- name: restart monoserve
  service:
    name: monoserve.service
    state: restarted
    enabled: yes

- name: restart monoserveApiSystem.service
  service: name=monoserveApiSystem.service  state=restarted

- name: Delete script
  file:
    path: /tmp/opensource-install.sh
    state: absent

- name: Create /credentials
  file:
    path: /credentials
    state: directory
    mode: 0755

- name: Create password.txt
  template:
    src: password.txt.j2
    dest: /credentials/password.txt
    mode: 0644

- name: Databases Random Password
  copy: 
    src: init.sh
    dest: /root/
    mode: 0750

# 开机自启脚本设置，其中 Ubuntu需提前创建 rc.local 文件
- block:
  - name: Setting rc.local
    file:
      path: /etc/rc.local
      state: touch
      mode: 0750

  - name: Write rc.local
    shell: echo "#!/bin/bash" > /etc/rc.local

  - name: restart rc.local
    service: name=rc.local state=restarted enabled=yes

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# 推送开机自启脚本
- name: Setting Startup
  lineinfile:
    path: /etc/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750
