---
- name: Create ONLYOFFICE user
  user:
    name: onlyoffice 
    shell: /user/sbin/nologin

- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: docker_gateway
  
- name: Create Directory /data/wwwroot/onlyoffice
  file:
    path: /data/wwwroot/onlyoffice
    state: directory
    owner: onlyoffice
    group: onlyoffice
    recurse: true

- name: Upload docker-compose.yml file
  template:
    src: docker-compose.yml
    dest: /data/wwwroot/onlyoffice

- name: Run the docker-compose
  shell: 
    cmd: docker-compose up
    chdir: /data/wwwroot/onlyoffice

- name: Create a symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: "/data/wwwroot/onlyoffice/docker-compose.yml",dest: "/data/config/apps-onlyoffice-compose.yml"}
    - {src: "/data/apps/onlyofficedocumentserver",dest: "/data/wwwroot/onlyofficedocumentserver"}
