---
- block:
  - name: Download OnlyOffice's auto-install script of Ubuntu&Debian
    get_url:
      url: "{{onlyoffice_debian_download}}"
      dest: /tmp/
      mode: 0755
    
  - name: install script
    command: /tmp/install-Debian.sh -os true

  when: ansible_os_family == 'Debian'


- block:
  - name: Download OnlyOffice's auto-install script of Redhat&CentOS
    get_url:
      url: "{{onlyoffice_redhat_download}}"
      dest: /tmp/
      mode: 0755
    
  - name: install script
    command: /tmp/install-RedHat.sh -os true 

  when: ansible_os_family == 'RedHat'


- name: Delete installation script
  file:
    path: /tmp/opensource-install.sh
    state: absent

# 处理数据库随机密码问题
# 从/var/www/onlyoffice/WebStudio/web.connections.config 文件中获取数据库密码，然后修改成123456便于随机化。
- name: get default root password of mysql
  shell: grep "Password" /var/www/onlyoffice/WebStudio/web.connections.config | awk -F\; '{print $4}' | awk -F'=' '{print $2}'
  register: reg_root_password

- debug: 
  msg: password is {{reg_root_password}}

- name: Create mysql user named onlyoffice
  mysql_user:
    name: onlyoffice
    password: "{{reg_root_password.stdout}}"
    login_user: root
    login_password: "{{reg_root_password.stdout}}"
    priv: 'onlyoffice.*:ALL'

- name: Change root user password to 123456
  mysql_user: 
    name: root
    password: "123456"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{reg_root_password.stdout}}"
    state: present
    
- name: replace root user in web.connections.config
  replace:
    path: /var/www/onlyoffice/WebStudio/web.connections.config
    before: ';Password'
    after: 'User ID='
    regexp: 'root'
    replace: 'onlyoffice'
