---
- name: Clone onlyoffice in Websoft9 
  git:
    repo: "{{onlyoffice_url}}"
    dest: "/data/wwwroot/onlyoffice"
    version: dev

- name: Create dir for onlyoffice
  file: 
    name: "/data/wwwroot/onlyoffice/{{item}}"
    state: directory
    recurse: yes
  loop:   
    - mail_data
    - mail_certs
    - mail_log
    - mail_mysql
    - document_data
    - document_log
    - document_forgotten
    - community_mysql
    - community_data
    - community_log
    - community_letsencrypt
    - controlpanel_data
    - controlpanel_log
    - mysql_data

- name: Run the docker-compose
  shell: |
    mv docker-compose.workspace.yml docker-compose.yml
    docker-compose -f up -d
    sleep 30
  args:
    chdir: /data/wwwroot/onlyoffice

- name: Check onlyofficecommunityserver Version
  shell: sudo echo "onlyofficecommunityserver version:" $(docker images |grep onlyoffice/communityserver |awk '{print $2}') | tee -a /data/logs/install_version.txt

- name: Check onlyofficedocumentserver Version
  shell: sudo echo "onlyofficedocumentserver version:" $(docker images |grep onlyoffice/documentserver |awk '{print $2}') | tee -a /data/logs/install_version.txt

- name: Check onlyofficecommunityserver Service
  shell: sudo docker ps | grep onlyofficecommunityserver
  register: check_onlyofficecommunityserver_service
  notify: check_onlyofficecommunityserver_service

- name: Check onlyofficedocumentserver Service
  shell: sudo docker ps | grep onlyofficedocumentserver
  register: check_onlyofficedocumentserver_service
  notify: check_onlyofficedocumentserver_service