# refer to: https://hub.docker.com/r/onlyoffice/documentserver and https://helpcenter.onlyoffice.com/server/docker/community/docker-installation.aspx
# refer to: https://github.com/ONLYOFFICE/Docker-CommunityServer/blob/master/docker-compose.yml
# ONLYOFFICE COMMUNITY EDITION= community server + document server + mail server
# This playbook have not mail server
# The environment item's value should not include "", otherwise mysql can't connected
# DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyofficedocumentserver is for integration

version: '2'
services:
  onlyoffice-communityserver:
    container_name: onlyofficecommunityserver
    image: onlyoffice/communityserver:latest
    environment:
      - MYSQL_SERVER_HOST={{docker_gateway.stdout}}
      - MYSQL_SERVER_PORT={{onlyoffice_db_port}}
      - MYSQL_SERVER_DB_NAME={{onlyoffice_db_database}}
      - MYSQL_SERVER_USER={{onlyoffice_db_user}}
      - MYSQL_SERVER_PASS={{onlyoffice_db_password}
      - MYSQL_SERVER_ROOT_PASSWORD={{onlyoffice_db_password}}
      - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyofficedocumentserver
    stdin_open: true
    restart: always
    volumes:
      - /data/wwwroot/onlyoffice/communityserver/logs:/var/log/onlyoffice
      - /data/wwwroot/onlyoffice/communityserver/data:/var/www/onlyoffice/Data
      - /data/wwwroot/onlyoffice/communityserver/documentserverdata:/var/www/onlyoffice/DocumentServerData
    ports:
      - '9003:80'
      - '5222:5222'

networks:
  default:
    external:
      name: "apps"
